### ISSUE TITLE
Problem with scannr

### ISSUE THREAD

**Issue by JannikSchneider12** [wh-xu/Hyper-Spec#2]
Hey,

I tested multiple runs of hyperspec for my mgf files and I have the problem that the scannr doesnt seem to be preserved, so it is always -1. Can somebody help me?

![image](https://github.com/wh-xu/Hyper-Spec/assets/72038436/e8a25ccd-ee89-49fc-925b-60066cd6ed56)

**Comment by wh-xu** [comment]
The SCAN number needs to be specifically shown in the MGF files. Here is an example:

BEGIN IONS
TITLE=controllerType=0 controllerNumber=1 scan=197
**SCANS=197**
RTINSECONDS=242.8862
PEPMASS=672.10693359375
CHARGE=2+
101.8324356 287.1295776367
112.0506973 1069.5451660156
...
